# How the plugin stores long-term data
# "external" data sources will also be used as messaging
storage:
  engines:
    mysql:
      # Whether or not to use MySQL/MariaDB
      # https://mariadb.org/
      enabled: false
      connection:
        # Address and port of the database instance
        address: '127.0.0.1:3306'
        # The name of the database the plugin will store data in
        # This must be created beforehand
        database: 'simple_staff_chat'
        # Table prefix for all plugin tables, indexes, keys, and procedures
        prefix: 'ssc_'
        # Database credentials
        username: ''
        password: ''
        # Extra options to use with the database server
        # These values will override any others
        options: 'useSSL=false&useUnicode=true&characterEncoding=utf8'
    redis:
      # Whether or not to use Redis for storage
      # https://redis.io/
      enabled: false
      connection:
        # Address and port of the Redis instance
        address: '127.0.0.1:6379'
        # Redis credentials
        password: ''
        # Storage prefix for all plugin data
        prefix: 'ssc:'
    sqlite:
      # Whether or not to use SQLite
      # https://www.sqlite.org/index.html
      enabled: true
      connection:
        # File name for the database
        file: 'simple_staff_chat.db'
        # Extra options to use with the database server
        # These values will override any others
        options: 'useUnicode=true&characterEncoding=utf8'
  settings:
    # The maximum size of the storage engine connection pool
    # Determines the max number of connections to storage engines
    max-pool-size: 4
    # The minimum size of the storage engine connection pool
    # Determines the min number of connections kept alive to storage engines
    min-idle: 4
    # The maximum lifetime of a connection in the pool
    # Should be at least 30 seconds less than any storage engine or infrastructure-imposed connection time limit
    max-lifetime: 1800000 # 30 minutes
    # The maximum number of milliseconds that the plugin will wait for a new connection from the pool before timing out
    timeout: 5000 # 5 seconds
  # The order in which the storage engines will be used
  # The first available engine will be considered the "master" and will be the authoritative data source
  # Keep in mind that, for redundancy, ALL defined and enabled storage engines will be used
  order:
    - 'mysql'
    - 'redis'
    - 'sqlite'

# How the plugin rapidly shares information with other servers along the network
messaging:
  engines:
    rabbitmq:
      # Whether or not to use RabbitMQ for messaging
      # https://www.rabbitmq.com/
      enabled: false
      connection:
        # Address and port of the RabbitMQ instance
        address: '127.0.0.1:5672'
        # RabbitMQ virtual host
        v-host: "/"
        # RabbitMQ credentials
        username: 'guest'
        password: 'guest'
    redis:
      # Whether or not to use Redis for messaging
      # https://redis.io/
      enabled: false
      connection:
        # Address and port of the Redis instance
        address: '127.0.0.1:6379'
        # Redis credentials
        password: ''
  settings:
    # The maximum size of the messaging engine connection pool
    # Determines the max number of connections to messaging engines
    max-pool-size: 5 # + 1 for the receiver
    # The minimum size of the messaging engine connection pool
    # Determines the min number of connections kept alive to messaging engines
    min-idle: 5 # + 1 for the receiver
    # The maximum lifetime of a connection in the pool
    # Should be at least 30 seconds less than any messaging engine or infrastructure-imposed connection time limit
    max-lifetime: 1800000 # 30 minutes
    # The maximum number of milliseconds that the plugin will wait for a new connection from the pool before timing out
    timeout: 5000 # 5 seconds
  # The order in which the messaging engines will be used
  # Keep in mind that, for redundancy, ALL defined and enabled messaging engines will be used
  order:
    - 'rabbitmq'
    - 'redis'

chat:
  # Commands to use for talking in admin chat
  commands:
    - 'sc'
    - 'ac'
    - 'ao'
  # Message format to use for admin chat
  format: '&6[&r{server}&r&6] [&r{level}&r&6] &b{player} &7>>&r {message}'
  # Whether or not to allow Minecraft color/format codes in chat messages
  allow-codes: true

# When true, logs some extra output to the console so you can see if/why things might be failing
debug: false

stats:
  # Whether or not to send anonymous usage statistics to bStats
  # True: Send anonymous stats; let the author know how well the plugin is doing and how it's used!
  # False: Do not send stats and make the author sad :(
  usage: true
  # Whether or not to send anonymous errors to the author
  # True: Send errors anonymously to GameAnalytics so the author can fix them!
  # False: Do not send errors and wonder why any bugs you encounter haven't been fixed
  errors: true

update:
  # Whether or not to automatically check for updates and notify the console if found
  check: true
  # Whether or not to notify players with the ae.admin permission node
  notify: true

# Config version, no touchy plz
version: 1.0