DROP TABLE IF EXISTS `ssc_data`;
CREATE TABLE `ssc_data` (
	"key"	TEXT NOT NULL UNIQUE,
	"value"	TEXT NOT NULL
)

DROP TABLE IF EXISTS `ssc_levels`;
CREATE TABLE `ssc_levels` (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL UNIQUE
)

INSERT INTO `ssc_levels` VALUES (1, 'ALL');

DROP TABLE IF EXISTS `ssc_servers`;
CREATE TABLE `ssc_servers` (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"uuid"	TEXT NOT NULL UNIQUE,
	"name"	TEXT NOT NULL
)

DROP TABLE IF EXISTS `ssc_players`;
CREATE TABLE `ssc_players` (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"uuid"	TEXT NOT NULL UNIQUE
)

DROP TABLE IF EXISTS `ssc_posted_chat`;
CREATE TABLE `ssc_posted_chat` (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"server_id"	INTEGER NOT NULL,
	"player_id"	INTEGER NOT NULL,
	"level"	INTEGER NOT NULL DEFAULT 1,
	"message"	TEXT NOT NULL,
	"date"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY("server_id") REFERENCES "ssc_servers"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY("player_id") REFERENCES "ssc_players"("id") ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY("level") REFERENCES "ssc_levels"("id") ON DELETE RESTRICT ON UPDATE CASCADE
)