PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS `{prefix}data`;
CREATE TABLE `{prefix}data` (
	"key"	TEXT NOT NULL UNIQUE,
	"value"	TEXT NOT NULL
);

DROP TABLE IF EXISTS `{prefix}levels`;
CREATE TABLE `{prefix}levels` (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL UNIQUE
);

INSERT INTO `{prefix}levels` VALUES (1, 'ALL');

DROP TABLE IF EXISTS `{prefix}servers`;
CREATE TABLE `{prefix}servers` (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"uuid"	TEXT NOT NULL UNIQUE,
	"name"	TEXT NOT NULL
);

DROP TABLE IF EXISTS `{prefix}players`;
CREATE TABLE `{prefix}players` (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"uuid"	TEXT NOT NULL UNIQUE
);

DROP TABLE IF EXISTS `{prefix}posted_chat`;
CREATE TABLE `{prefix}posted_chat` (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"server_id"	INTEGER NOT NULL,
	"player_id"	INTEGER NOT NULL,
	"level"	INTEGER NOT NULL DEFAULT 1,
	"message"	TEXT NOT NULL,
	"date"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY("server_id") REFERENCES "{prefix}servers"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY("player_id") REFERENCES "{prefix}players"("id") ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY("level") REFERENCES "{prefix}levels"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

PRAGMA foreign_keys = ON;